"""create_deviations_table

Revision ID: 12ad37734251
Revises: 
Create Date: 2026-09-26 18:56:54.397679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12ad37734251'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deviations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.Enum('Draft', 'Logged', name='statusenum'), nullable=False),
    sa.Column('input_source', sa.Enum('pdf', 'pasted_text', name='inputsourceenum'), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('raw_input_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('batch_number', sa.String(length=255), nullable=True),
    sa.Column('equipment_id', sa.String(length=255), nullable=True),
    sa.Column('process_parameter', sa.String(length=255), nullable=True),
    sa.Column('standard_value', sa.String(length=255), nullable=True),
    sa.Column('actual_value', sa.String(length=255), nullable=True),
    sa.Column('deviation_duration', sa.String(length=255), nullable=True),
    sa.Column('date_of_occurrence', sa.String(length=100), nullable=True),
    sa.Column('detected_by', sa.String(length=255), nullable=True),
    sa.Column('immediate_action_taken', sa.Text(), nullable=True),
    sa.Column('impact_assessment', sa.Text(), nullable=True),
    sa.Column('severity', sa.Enum('Critical', 'Major', 'Minor', name='severityenum'), nullable=True),
    sa.Column('severity_reason', sa.Text(), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deviations_id'), 'deviations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deviations_id'), table_name='deviations')
    op.drop_table('deviations')
    # ### end Alembic commands ###
