"""schema_realignment_v2

Revision ID: 741d28d5ff29
Revises: 12ad37734251
Create Date: 2026-09-27 03:01:26.918640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '741d28d5ff29'
down_revision: Union[str, None] = '12ad37734251'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deviations', sa.Column('site_plant', sa.String(length=255), nullable=True))
    op.add_column('deviations', sa.Column('source', sa.Enum('Production Floor', 'Laboratory', 'Audit Finding', 'Regulatory Inspection', 'Self-Reported', 'Other', name='sourceenum'), nullable=True))
    op.add_column('deviations', sa.Column('related_product_material', sa.String(length=500), nullable=True))
    op.add_column('deviations', sa.Column('batch_lot_number', sa.String(length=255), nullable=True))
    op.add_column('deviations', sa.Column('detailed_description', sa.Text(), nullable=True))
    op.add_column('deviations', sa.Column('initial_severity', sa.Enum('Critical', 'Major', 'Minor', name='severityenum'), nullable=True))
    op.add_column('deviations', sa.Column('initial_impact', sa.Enum('No Impact', 'Minor Impact', 'Major Impact', 'Critical Impact', name='initialimpactenum'), nullable=True))
    op.add_column('deviations', sa.Column('suggested_next_action', sa.Text(), nullable=True))
    op.drop_column('deviations', 'impact_assessment')
    op.drop_column('deviations', 'standard_value')
    op.drop_column('deviations', 'department')
    op.drop_column('deviations', 'process_parameter')
    op.drop_column('deviations', 'description')
    op.drop_column('deviations', 'detected_by')
    op.drop_column('deviations', 'batch_number')
    op.drop_column('deviations', 'product_name')
    op.drop_column('deviations', 'actual_value')
    op.drop_column('deviations', 'equipment_id')
    op.drop_column('deviations', 'severity')
    op.drop_column('deviations', 'deviation_duration')
    op.drop_column('deviations', 'immediate_action_taken')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deviations', sa.Column('immediate_action_taken', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True))
    op.add_column('deviations', sa.Column('deviation_duration', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    op.add_column('deviations', sa.Column('severity', mysql.ENUM('Critical', 'Major', 'Minor', collation='utf8mb4_unicode_ci'), nullable=True))
    op.add_column('deviations', sa.Column('equipment_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    op.add_column('deviations', sa.Column('actual_value', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    op.add_column('deviations', sa.Column('product_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    op.add_column('deviations', sa.Column('batch_number', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    op.add_column('deviations', sa.Column('detected_by', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    op.add_column('deviations', sa.Column('description', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True))
    op.add_column('deviations', sa.Column('process_parameter', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    op.add_column('deviations', sa.Column('department', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    op.add_column('deviations', sa.Column('standard_value', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    op.add_column('deviations', sa.Column('impact_assessment', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True))
    op.drop_column('deviations', 'suggested_next_action')
    op.drop_column('deviations', 'initial_impact')
    op.drop_column('deviations', 'initial_severity')
    op.drop_column('deviations', 'detailed_description')
    op.drop_column('deviations', 'batch_lot_number')
    op.drop_column('deviations', 'related_product_material')
    op.drop_column('deviations', 'source')
    op.drop_column('deviations', 'site_plant')
    # ### end Alembic commands ###
